<?php
/*
Plugin Name: #Gym Member Plugin
Plugin URI: https://www.sufyan.in/
Description: This plugin code is generated by Sufyan Code Generator.
Version: 0.1
Author: Sufyan
Author URI: https://www.sufyan.in/code-generator/
License: GPLv2 or later
Text Domain: sufyan
*/
//$wpdb->show_errors(); $wpdb->print_error();

function gym_member_1589529766_admin_menu(){
    add_menu_page('Gym Member','Gym Member','manage_options','gym_member_admin','gym_member_ewb','dashicons-admin-users','2');
}
add_action('admin_menu' , 'gym_member_1589529766_admin_menu');

/* -- Declaring all functions, _ewb suffix added -- */
function gym_member_ewb(){ include (dirname(__FILE__).'/gym_member.php'); }

function gym_member_1589529766_activate() {
    global $wpdb;
    $table_name = "gym_member";
    $charset_collate = $wpdb->get_charset_collate();
    $sql = "CREATE TABLE $table_name (
        id int NOT NULL AUTO_INCREMENT,
        gym_member text NULL,
        gender text NULL,
        phone text NULL,
        email text NULL,
        start_date text NULL,
        end_date text NULL,
        fees text NULL,
        slot text NULL,
        trainee text NULL,
        status text NULL,
        PRIMARY KEY  (id)
        ) $charset_collate;";
    require_once( ABSPATH . "wp-admin/includes/upgrade.php" );
    dbDelta( $sql );
}
register_activation_hook( __FILE__, "gym_member_1589529766_activate" );

require_once( 'BFIGitHubPluginUploader.php' );
if ( is_admin() ) {
    new BFIGitHubPluginUpdater( __FILE__, 'sufyan-sheikh', "hs-gym-members" );
}
